### ISSUE TITLE
Converting to package

### ISSUE THREAD

**Issue by Trudko** [pitaj/atom-resize-panes#1]
Hi :), you've mentioned that you don't want to learn the coffee script just so you can turn this into package, but you can have javascript pacakges too in Atom , so I am bit confused.

**Comment by pitaj** [comment]
I realize that it is indeed possible to use JavaScript. However, the atom
docs are coffeescript only, and I'm not going to bother converting them to
JavaScript. If you can point me to an example plugin built in JavaScript or
some documentation for JS, I'd be happy to convert this into a plugin
myself.

**Comment by Trudko** [comment]
What I did was compile existing packages using https://atom.io/packages/coffee-compile. You can also experiment with Atom api directly from Chromium toolbar if you are not sure.

**Comment by b-long** [comment]
:+1: Would really like to see this as a package.  This may help you get started using vanilla JS: http://blog.fxndev.com/create-your-first-atom-package-in-js/ .  Alternatively, this plugin already exists: https://atom.io/packages/pane-layout-plus

**Comment by pitaj** [comment]
This is in Atom core now.

**Comment by pitaj** [comment]
Closing cuz deprecated
