### ISSUE TITLE
Cannot read property 'getFlexScale' of undefined

### ISSUE THREAD

**Issue by admix** [pitaj/atom-resize-panes#4]
This issue appears when I click on the resize pane. The resizing actually works fine, but this issue keeps shouting. Could might because of the latest atom realese (0.209)

Cannot read property 'getFlexScale' of undefined:

```
TypeError: Cannot read property 'getFlexScale' of undefined
  at atom-pane-resize-handle.PaneResizeHandleElement.setFlexGrow (C:\Users\username\AppData\Local\atom\app-0.209.0\resources\app.asar\src\pane-resize-handle-element.js:62:34)
  at atom-pane-resize-handle.PaneResizeHandleElement.resizePane (C:\Users\username\AppData\Local\atom\app-0.209.0\resources\app.asar\src\pane-resize-handle-element.js:86:21)
```

**Comment by pitaj** [comment]
This isn't compatible with the latest version of atom. It has the
functionality already built in.

**Comment by pitaj** [comment]
Also, are you using the package version? Because I didn't publish that and
don't maintain it.

**Comment by admix** [comment]
I downloded directly from github and installed manually. The resize that is included with atom is not working properly for me..maybe they haven't released that yet.

**Comment by pitaj** [comment]
What do you mean the core version isn't working? There aren't any handles
in core.

**Comment by pitaj** [comment]
Did you pull the master branch or the package branch? I know the master
branch used to work in older atom versions. I don't know about the package branch.

**Comment by admix** [comment]
I got the one linked to the link in the readme. 
PS: I thought you said that atom has a built in solution for the resizing..

**Comment by pitaj** [comment]
Now, atom has pane resize in core. The error is caused by the core feature trying to do stuff.

**Comment by admix** [comment]
Ok thanks, closing it.
